# Role that return information regarding the operational state of the interfaces of a switch

- name: issue a show interfaces command and return the output
  ios_command:
    commands: show interfaces
  register: output

- name: generate structured show_interfaces output
  set_fact:
    result: "{{ (output.stdout[0] | parse_cli('filters/show_interfaces.yml')) }}"

- name: debug result
  debug:
    var: result
