- include: show_interfaces.yml

- set_fact:
    show_interfaces_result: "{{ result }}"

- include: show_interfaces_switchport.yml

- set_fact:
    show_interfaces_switchport_result: "{{ result }}"
    
- set_fact:
    result: "{{ {} }}"

- set_fact:
    result: "{{ result | combine({ item[0].name: item[0] | combine(item[1]) }) }}"
  when: "{{ item[0].name == item[1].name }}"
  with_nested: 
    - "{{ show_interfaces_result.interfaces }}"
    - "{{ show_interfaces_switchport_result.interfaces }}"