- include: show_interfaces.yml

- set_fact:
    show_interfaces_result: "{{ result }}"

- include: show_interfaces_switchport.yml

- set_fact:
    show_interfaces_switchport_result: "{{ result }}"

- name: generate result
  lists_to_dict:
    list_1: "{{ show_interfaces_result.interfaces }}"
    list_2: "{{ show_interfaces_switchport_result.interfaces }}"
    key: name
  register: result

- name: store output in variable
  set_fact:
    output_1: '{{ result.msg }}'

- debug:
    var: output_1

- name: get mac address-table information
  include_role:
    name: get_mac_address_table

- name: store output in variable
  set_fact:
    output_2: '{{ result.msg }}'

- debug:
    var: output_2

- name: combine output_1 and output_2 in a single result
  merge_dictionaries:
    dict_1: '{{ output_1 }}'
    dict_2: '{{ output_2 }}'
  register: result