# Role that return the information displayed in the show interfaces switchport in a structured way

- name: issue a show interfaces switchport command and register the output
  ios_command:
    commands: show interfaces switchport
  register: output

- name: generate structured show_interfaces_switchport output
  set_fact:
    result: "{{ (output.stdout[0] | parse_cli('filters/show_interfaces_switchport.yml')) }}"
