all:
  vars:
    ansible_user: conatel
    ansible_ssh_pass: C0n4t3l.
    ansible_connection: network_cli
  hosts:
    172.16.1.55:
  children:
    ios:
      vars:
        ansible_network_os: ios
        ansible_become: True
        ansible_become_method: enable
        ansible_connection: network_cli
      hosts:
        172.16.1.55:
        200.58.153.100:
      children:
        lab:
          children:
            sw_cliente_demo:
              hosts:
                172.16.1.55:
              vars:
                netconf_username: netconf_username
                netconf_password: C0n4t3l.
            sw_pelado:
              hosts:
                200.58.153.100:
              vars:
                ansible_port: 2222
                ansible_user: ialmandos
                ansible_ssh_pass: ialmandos
