- name: issue show mac address-table command and register the result
  ios_command:
    commands:
      - show mac address-table
  register: output

- name: generate structured output
  set_fact:
    result: "{{ (output.stdout[0] | parse_cli('filters/show_mac_address_table.yml')) }}"
  
- name: transform structured output to dictionary with port names as keys
  list_to_dict:
    list: '{{ result.entries }}'
    key: port
    list_name: mac_entries
  register: result