# Role that returns os, platform and version of a switch in a structured way
# Format of the output:
# {
#   'os': 'IOS',
#   'platform': 'C2960',
#   'version': '2.2(55)SE7'
#}

- name: Issue show version command and return the output
  ios_command:
    commands: show version
  register: output

- name: generate structured show_version output
  set_fact:
    result: "{{ (output.stdout[0] | parse_cli('filters/show_version.yml')).show_version[0] }}"
