# Role that return information regarding the operational state of the interfaces of a switch

- name: issue a show vlan command and return the output
  ios_command:
    commands: show vlan
  register: output

- name: generate structured show_vlan output
  set_fact:
    result: "{{ (output.stdout[0] | parse_cli('filters/show_vlan.yml')) }}"

- name: debug result
  debug:
    var: result
